name: Lint Workflows

on:
  pull_request:
    paths: ['.github/workflows/**']

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    uses: zentala/.github/.github/workflows/reusable-lint-workflows.yml@main
